//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace table_whatsapp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aduan_Whatsapp
    {
        public int Id { get; set; }
        public string No { get; set; }
        public string Pengadu { get; set; }
        public string Tarikh { get; set; }
        public string Jenis_Aduan { get; set; }
        public string Bahagian { get; set; }
        public string Jenis_Pertanyaan { get; set; }
        public string Aduan { get; set; }
        public string Tindakan { get; set; }
        public string Nama { get; set; }
        public string Status { get; set; }
        public System.DateTime Tarikh_aduan { get; set; }
        public string Tarikh_selesai { get; set; }
    }
}
